wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.3.dev1
    code_path: code/main.py
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1628878898
    t:
      4: 3.6.8
      5: 0.11.3.dev1
      8:
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 15
learning_rate:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.1
seed:
  desc: null
  value: 10
